"""add_universe_tables

Revision ID: 7237d5cf30fe
Revises: 6366a6094b63
Create Date: 2025-11-20 19:32:18.928092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7237d5cf30fe"
down_revision: Union[str, None] = "6366a6094b63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "universes",
        sa.Column("universe_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("BACKTEST", "PRODUCTION", name="universemode"),
            nullable=False,
        ),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("config_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_symbols", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("universe_id"),
    )
    op.create_table(
        "universe_symbols",
        sa.Column("universe_id", sa.Integer(), nullable=False),
        sa.Column("ticker_id", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"], ["tickers.ticker_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["universe_id"], ["universes.universe_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("universe_id", "ticker_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("universe_symbols")
    op.drop_table("universes")
    op.execute("DROP TYPE IF EXISTS universemode")
    # ### end Alembic commands ###
